runtime: python
env: flex
entrypoint: uwsgi --http :$PORT --wsgi-file manage.py --module manage --callable app  --gevent 5000


runtime_config:
  python_version: 2

# [START env_variables]
env_variables:
    ELASTICSEARCH_URL: http://10.142.0.3:9200
# [END env_variables]