version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      # - image: elasticsearch
      - image: circleci/python:2.7
        # environment:
          # FLASK_CONFIG: testing
    steps:
      - checkout
      - restore_cache:
          key: deps-a-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install requirements.txt
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-a-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests that do not depend on ES
          command: |
            . venv/bin/activate
            python -m pytest
      # - store_artifacts:
          # path: test-reports/
          # destination: tr1
      # - store_test_results:
          # path: test-reports/      
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t circle-${CIRCLE_SHA1} .
      - run:
          name: Push to GCR
          command: |
            docker login -u _json_key -p "${GCR_JSON_KEY_FILE}" https://eu.gcr.io
            ## branch tag and push
            docker tag circle-${CIRCLE_SHA1} ${GCR_REPO}:${CIRCLE_BRANCH}
            docker push ${GCR_REPO}:${CIRCLE_BRANCH}
            ## SHA commit push
            docker tag ${GCR_REPO}:${CIRCLE_BRANCH} ${GCR_REPO}:circle-${CIRCLE_SHA1}
            docker push ${GCR_REPO}:circle-${CIRCLE_SHA1}
            ## push latest if master
            if [ "$CIRCLE_BRANCH" = "master" ]
              then
                docker tag ${GCR_REPO}:${CIRCLE_BRANCH} ${GCR_REPO}:latest
                docker push ${GCR_REPO}:latest
            fi
      - run:
          name: Push to Quay
          command: |
            docker login -u="opentargets+quaybot" -p="${QUAYBOT_PASSWORD}" quay.io
            ## branch tag and push
            docker tag circle-${CIRCLE_SHA1} ${QUAY_REPO}:${CIRCLE_BRANCH}
            docker push ${QUAY_REPO}:${CIRCLE_BRANCH}
            ## sha commit push
            docker tag ${QUAY_REPO}:${CIRCLE_BRANCH} ${QUAY_REPO}:circle-${CIRCLE_SHA1}
            docker push ${QUAY_REPO}:circle-${CIRCLE_SHA1}
            ## push latest if master
            if [ "$CIRCLE_BRANCH" = "master" ] 
              then
                docker tag ${QUAY_REPO}:${CIRCLE_BRANCH} ${QUAY_REPO}:latest
                docker push ${QUAY_REPO}:latest
            fi

  deploy:
    working_directory: ~/circulate
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Decode Google Cloud Credentials
          command: echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
      - run:
          name: Authenticate to Google Cloud
          command: |
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: configure google cloud endpoints
          command: |
            cd app/static/docs/swagger 
            echo ">> Checking if swagger.yaml is one of the files changed in this commit"
            git diff-tree --no-commit-id --name-only -r HEAD 
            git diff-tree --no-commit-id --name-only -r HEAD | while read filename; do
              if [ "$filename" == "app/static/docs/swagger/swagger.yaml" ]; then
                echo ">> swagger.yaml changed. redeploying endpoints configuration..."
                gcloud service-management deploy swagger.yaml
              else
                echo ">> swagger.yaml not changed in the latest commit."
                echo ">> Keeping the same Endpoints configuration"
              fi
            done 
      - run:
          name: Substitute ENV vars for deploy
          command: |
            bash .circleci/render.sh app.yaml.template > ~/circulate/app.yaml
      - run:
          name: Deploy branch to google AppEngine
          #NOTE: this creates another docker container with a uWSGI app and no NGINX in front
          command: |
            gcloud version
            gcloud app deploy --no-promote --version $CIRCLE_BRANCH --project $GOOGLE_PROJECT_ID
      - run:
          name: Trigger runscope dev-k8s tests on deployed branch
          command: |
            pip install -r .circleci/runscope/requirements.txt
            python .circleci/runscope/app.py https://api.runscope.com/radar/${RUNSCOPE_TEST_UUID}/trigger?runscope_environment=${RUNSCOPE_ENV_UUID_EU_DEV}&host=${CIRCLE_BRANCH}-dot-${GOOGLE_PROJECT_ID}.appspot.com


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build	
          # filters:
          #   branches:
          #     only: master
